name: cd

on:
  push:
    # tags:
      # - '*'

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0']
        channel: [ Dev, Prod_Sideload, Prod_Store ]
        targetPlatform: [ Any CPU ]
        include:
          # includes the following variables for the matrix leg matching Prod_Sideload
          - channel: Prod_Sideload
            Configuration: Release
            ChannelName: Prod_Sideload
            #DistributionUrl: https://microsoft.github.io/github-actions-for-desktop-apps-distribution-prod
            MsixPackageId: ElevenPercent.ProdSideload
            MsixPublisherId: CN=jmorjsm
            MsixPackageDisplayName: ElevenPercent (ProdSideload)

    steps: # Update the appxmanifest before build by setting the per-channel values set in the matrix.
      - uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.201
          
#       - name: Update manifest version
#         run: |
#           [xml]$manifest = get-content ".\$env:Wap_Project_Directory\Package.appxmanifest"
#           $manifest.Package.Identity.Version = "$env:NBGV_SimpleVersion.0"
#           $manifest.Package.Identity.Name = "${{ matrix.MsixPackageId }}"
#           $manifest.Package.Identity.Publisher = "${{ matrix.MsixPublisherId }}"
#           $manifest.Package.Properties.DisplayName = "${{ matrix.MsixPackageDisplayName }}"
#           $manifest.Package.Applications.Application.VisualElements.DisplayName = "${{ matrix.MsixPackageDisplayName }}"
#           $manifest.save(".\$env:Wap_Project_Directory\Package.appxmanifest")

      - name: Set env variables
        run : |
          "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $env:GITHUB_ENV
 
      # Add  MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.0
      
      # Restore the application
      - name:  Restore the application to populate the obj folder
        run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: Debug

      # Build the Windows Application Packaging project for Dev and Prod_Sideload
      - name: publish self-contained app
        run: dotnet publish $env:Solution_Path --configuration=$env:Configuration --self-contained true
        if: matrix.ChannelName != 'Prod_Sideload'
        env:
          Configuration: ${{ matrix.Configuration }}
          TargetPlatform: ${{ matrix.targetplatform }}
      
      - name: tree
        run : |
          tree .

      - name: zip
        run: |
          Compress-Archive -DestinationPath Eleven-Percent.zip -Path Eleven-Percent\bin\${{matrix.Configuration}}\net7.0-windows\
    
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Eleven-Percent.zip
