name: ci

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0']
        channel: [ Dev, Prod_Sideload, Prod_Store ]
        targetPlatform: [ x86, x64 ]
        include:
          
          # includes the following variables for the matrix leg matching Dev
          - channel: Dev
            ChannelName: Dev
            Configuration: Debug
            #DistributionUrl: https://microsoft.github.io/github-actions-for-desktop-apps-distribution-dev
            MsixPackageId: ElevenPercent.Dev
            MsixPublisherId: CN=jmorjsm
            MsixPackageDisplayName: ElevenPercent (Dev)
          
          # includes the following variables for the matrix leg matching Prod_Sideload
          - channel: Prod_Sideload
            Configuration: Release
            ChannelName: Prod_Sideload
            #DistributionUrl: https://microsoft.github.io/github-actions-for-desktop-apps-distribution-prod
            MsixPackageId: ElevenPercent.ProdSideload
            MsixPublisherId: CN=jmorjsm
            MsixPackageDisplayName: ElevenPercent (ProdSideload)
          
          # includes the following variables for the matrix leg matching Prod_Store
          - channel: Prod_Store
            Configuration: Release
            ChannelName: Prod_Store
            DistributionUrl:
            MsixPackageId: ElevenPercent.ProdStore
            MsixPublisherId: CN=jmorjsm
            MsixPackageDisplayName: ElevenPercent (ProdStore)

    steps:
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0

      # Add  MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.0
      
      # Restore the application
      - name:  Restore the application to populate the obj folder
        run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
        env:
          Configuration: Debug
          RuntimeIdentifier: win-${{ matrix.targetplatform }}
          
      # Build the Windows Application Packaging project
      - name: Build the Windows Application Packaging Project (wapproj)
        run: msbuild $env:Solution_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
        env:
          AppxBundle: Never
          BuildMode: SideLoadOnly
          Configuration: Release
          TargetPlatform: ${{ matrix.targetplatform }}
          
      # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: MSIX Package
          path: ElevenPercent.Package\AppPackages\